### ISSUE TITLE
Fails compiling GBox2d

### ISSUE THREAD

**Issue by isc** [utkarshkukreti/rubymotion-cocos2dbox2dtest#1]
Hi,

I cloned your project and tried building it but it fails when compiling GBox2d with the following message:
./GB2Contact.h:28:9: fatal error: 'cocos2d.h' file not found

Did you manage to get it to work properly ?

**Comment by utkarshkukreti** [comment]
Nope, I was getting the same error. Haven't tried since then, as I'm not doing RubyMotion much these days.
